#!/bin/env python

import os, argparse, math, collections, json, operator
from datetime import date

def getFile(inputDir, plotsDir, name):

    path = "./%s"%(plotsDir)
    if os.path.isfile("%s/%s/%s.pdf"%(inputDir,plotsDir,name)):
        path += "%s}.pdf"%(name)
    elif os.path.isfile("%s/%s/%s.png"%(inputDir,plotsDir,name)):               
        path += "%s}.png"%(name)
    else:
        path = "NULL}"
   
    return path

def writeHeader(talk, date, title):

    talk.write(r"\documentclass[usenames,dvipsnames]{beamer}")
    talk.write("\n")
    talk.write(r"\input{master_preamble.tex}")
    talk.write("\n")
    talk.write(r"\let\underscore\_")
    talk.write("\n")
    talk.write(r"\newcommand{\myunderscore}{\renewcommand{\_}{\underscore\hspace{0pt}}}")
    talk.write("\n")
    talk.write(r"\myunderscore")
    talk.write("\n")
    talk.write(r"\author[Bryan Crossman]{B. Crossman}")
    talk.write("\n")
    talk.write(r"\institute[]{University of Minnesota}")
    talk.write("\n")
    talk.write(r"\date[%s]{%s}"%(date,date))
    talk.write("\n")
    talk.write(r"\title[Stealth Stop Meeting]{%s}"%(title))
    talk.write("\n")
    talk.write(r"\subtitle[Exploring the Double DisCo]{}")
    talk.write("\n")
    talk.write(r"\titlegraphic{\includegraphics[width=2.15cm]{goldy.pdf}}")
    talk.write("\n")
    talk.write(r"\institute[]{%")
    talk.write("\n")
    talk.write(r"\medskip")
    talk.write("\n")
    talk.write("}\n")
    talk.write("\n")
    talk.write(r"\begin{document}")
    talk.write("\n")
    talk.write("\n")
    talk.write(r"\titlefooter")
    talk.write("\n")
    talk.write(r"\begin{frame}")
    talk.write("\n")
    talk.write(r"    \titlepage")
    talk.write("\n")
    talk.write(r"\end{frame}")
    talk.write("\n")
    talk.write("}\n\n")
    talk.write(r"\mainfooter")
    talk.write("\n")

def writeFooter(talk):

    talk.write("\end{document}")

def writeSlide1(talk, s, inputDir, plotsDir, title):

    talk.write(r"\begin{frame}")
    talk.write("\n")
    talk.write(r"\tiny %s\medskip"%(title))
    talk.write("\n\n")
    talk.write(r"%s"%(s))
    talk.write("\n")
    talk.write(r"\begin{columns}")
    talk.write("\n")
    talk.write(r"\begin{column}{1.0\textwidth}")
    talk.write("\n")
    talk.write(r"    \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"        \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0 0 1cm 0,clip,width=0.30\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "mass_split_val")))
    talk.write("\n")
    talk.write(r"        \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"        \end{scope}")
    talk.write("\n")
    talk.write(r"    \end{tikzpicture}")
    talk.write("\n")
    talk.write(r"    \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"        \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0 0 1cm 0,clip,width=0.30\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "output_loss_val")))
    talk.write("\n")
    talk.write(r"        \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"        \end{scope}")
    talk.write("\n")
    talk.write(r"    \end{tikzpicture}")
    talk.write("\n")
    talk.write(r"    \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"        \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0 0 2cm 0,clip,width=0.30\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "NonClosure_vs_Disc1Disc2_Njets7")))
    talk.write("\n")
    talk.write(r"        \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"        \end{scope}")
    talk.write("\n")
    talk.write(r"    \end{tikzpicture}")
    talk.write("\n")
    talk.write(r"\end{column}")
    talk.write("\n")
    talk.write(r"\end{columns}")
    talk.write("\n")
    talk.write(r"\centering")
    talk.write("\n")
    talk.write(r"\Wider[0.5em]{%")
    talk.write("\n")
    talk.write(r"\begin{columns}")
    talk.write("\n")
    talk.write(r"\begin{column}{0.33\textwidth}")
    talk.write("\n")
    talk.write(r"    \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"        \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=1.0cm 0.1cm 1.2cm 0,clip,width=1.0\linewidth]{{%s}};"%(getFile(inputDir, plotsDir,"Njets_Region_A_PredVsActual")))
    talk.write("\n")
    talk.write(r"        \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"        \end{scope}")
    talk.write("\n")
    talk.write(r"    \end{tikzpicture}")
    talk.write("\n")
    talk.write(r"\end{column}")
    talk.write("\n")
    talk.write(r"\begin{column}{0.33\textwidth}")
    talk.write("\n")
    talk.write(r"    \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"        \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0 0 3cm 0,clip,width=1.0\linewidth]{{%s}};"%(getFile(inputDir, plotsDir,"2D_BG_Disc1VsDisc2_Njets7")))
    talk.write("\n")
    talk.write(r"        \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"            \node[align=center,anchor=center] at (0.53,0.92) {\resizebox{!}{5pt}{\mboldcol{UMNMaroon}{BG}}};")
    talk.write("\n")
    talk.write(r"        \end{scope}")
    talk.write("\n")
    talk.write(r"    \end{tikzpicture}")
    talk.write("\n")
    talk.write(r"\end{column}")
    talk.write("\n")
    talk.write(r"\begin{column}{0.33\textwidth}")
    talk.write("\n")
    talk.write(r"    \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"        \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0 0 3cm 0,clip,width=1.0\linewidth]{{%s}};"%(getFile(inputDir, plotsDir,"2D_SG550_Disc1VsDisc2_Njets7")))
    talk.write("\n")
    talk.write(r"        \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"            \node[align=center,anchor=center] at (0.53,0.92) {\resizebox{!}{5pt}{\mboldcol{UMNMaroon}{SG}}};")
    talk.write("\n")
    talk.write(r"        \end{scope}")
    talk.write("\n")
    talk.write(r"    \end{tikzpicture}")
    talk.write("\n")
    talk.write(r"\end{column}")
    talk.write("\n")
    talk.write(r"\end{columns}")
    talk.write("\n")
    talk.write(r"}")
    talk.write("\n")
    talk.write(r"\end{frame}")
    talk.write("\n")

def writeSlide2(talk, inputDir, plotsDir, title):

    talk.write(r"\begin{frame}")
    talk.write("\n")
    talk.write(r"    \vspace*{-0.3cm}")
    talk.write("\n")
    talk.write(r"    \Wider[2.5em]{%")
    talk.write("\n")
    talk.write(r"    \scriptsize")
    talk.write("\n")
    talk.write(r"    \begin{tabular}{C{0.15\textwidth} C{0.15\textwidth} C{0.15\textwidth} C{0.15\textwidth} C{0.15\textwidth}}")
    talk.write("\n")
    talk.write(r"        \mboldcol{UMNMaroon}{$\njets=7$} & \mboldcol{UMNMaroon}{$\njets=8$} & \mboldcol{UMNMaroon}{$\njets=9$} & \mboldcol{UMNMaroon}{$\njets=10$} & \mboldcol{UMNMaroon}{$\njets=11$}\\ ")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "2D_BG_Disc1VsDisc2_Njets7")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{BG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}&")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "2D_BG_Disc1VsDisc2_Njets8")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{BG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}&")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "2D_BG_Disc1VsDisc2_Njets9")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{BG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}&")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "2D_BG_Disc1VsDisc2_Njets10")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{BG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}&")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "2D_BG_Disc1VsDisc2_Njets11")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{BG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}")
    talk.write("\n")
    talk.write(r"    \end{tabular}")
    talk.write("\n")
    talk.write(r"    \begin{tabular}{C{0.15\textwidth} C{0.15\textwidth} C{0.15\textwidth} C{0.15\textwidth} C{0.15\textwidth}}")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "2D_SG550_Disc1VsDisc2_Njets7")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{SG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}&")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "2D_SG550_Disc1VsDisc2_Njets8")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{SG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}&")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "2D_SG550_Disc1VsDisc2_Njets9")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{SG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}&")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "2D_SG550_Disc1VsDisc2_Njets10")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{SG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}&")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "2D_SG550_Disc1VsDisc2_Njets11")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{SG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}")
    talk.write("\n")
    talk.write(r"    \end{tabular}")
    talk.write("\n")

    talk.write(r"    \begin{tabular}{C{0.15\textwidth} C{0.15\textwidth} C{0.15\textwidth} C{0.15\textwidth} C{0.15\textwidth}}")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "NonClosure_vs_Disc1Disc2_Njets7")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{SG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}&")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "NonClosure_vs_Disc1Disc2_Njets8")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{SG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}&")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "NonClosure_vs_Disc1Disc2_Njets9")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{SG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}&")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "NonClosure_vs_Disc1Disc2_Njets10")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{SG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}&")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "NonClosure_vs_Disc1Disc2_Njets11")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{SG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}")
    talk.write("\n")
    talk.write(r"    \end{tabular}")
    talk.write("\n")

    talk.write(r"    \begin{tabular}{C{0.15\textwidth} C{0.15\textwidth} C{0.15\textwidth} C{0.15\textwidth} C{0.15\textwidth}}")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "Sign_vs_Disc1Disc2_Njets7")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{SG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}&")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "Sign_vs_Disc1Disc2_Njets8")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{SG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}&")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "Sign_vs_Disc1Disc2_Njets9")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{SG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}&")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "Sign_vs_Disc1Disc2_Njets10")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{SG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}&")
    talk.write("\n")
    talk.write(r"        \begin{tikzpicture}")
    talk.write("\n")
    talk.write(r"            \node[anchor=south west,inner sep=0] (image) {\includegraphics[trim=0.95cm 0 3cm 0,clip,width=\linewidth]{{%s}};"%(getFile(inputDir, plotsDir, "Sign_vs_Disc1Disc2_Njets11")))
    talk.write("\n")
    talk.write(r"            \begin{scope}[x={(image.south east)},y={(image.north west)}]")
    talk.write("\n")
    talk.write(r"                \node[align=center,anchor=center] at (0.51,0.92) {\resizebox{!}{3pt}{\mboldcol{UMNMaroon}{SG}}};")
    talk.write("\n")
    talk.write(r"            \end{scope}")
    talk.write("\n")
    talk.write(r"        \end{tikzpicture}")
    talk.write("\n")
    talk.write(r"    \end{tabular}")
    talk.write("\n")

    talk.write(r"    }")
    talk.write("\n")
    talk.write(r"\end{frame}")
    talk.write("\n")
    talk.write(r"")
    talk.write("\n")

if __name__ == '__main__':
    usage = "usage: %prog [options]"
    parser = argparse.ArgumentParser(usage)
    parser.add_argument("--inputDir", dest="inputDir", help="Directory to make talk", type=str, required=True) 
    parser.add_argument("--subdir",   dest="subdir",   help="Special subdir name",    type=str, default="") 
    parser.add_argument("--title",    dest="title",    help="Title of talk",          type=str, default="A SUPER SWWETT TITLE", nargs="+") 

    args = parser.parse_args()

    today = date.today()

    date1 = today.strftime("%Y%m%d")
    date2 = today.strftime("%-d %B %Y")

    stop = 100

    path = "%s/%s"%(args.inputDir,args.subdir)

    trainings = sorted(os.listdir(path))
    tDict = {}; mDict = {}
    for training in trainings:
        tempS = "" 
        if os.path.isfile("%s/%s"%(path,training)): continue

        temp = os.listdir("%s/%s"%(path,training))

        if len(temp) < 5 or not os.path.exists("%s/%s/config.json"%(path,training)): continue

        if os.path.exists("%s/%s/config.json"%(path,training)):
            f = open("%s/%s/config.json"%(path,training), "r")
            config = json.load(f)
            #tempS = "Closure $\chi^2/\\text{ndof}=%3.2f$ ----- Sign. = %3.2f ----- $\langle\\text{CC}\\rangle$ = %3.2f ----- $\sigma_{\\text{CC}} = %3.2f$"%(config["Achi2ndof"], config["TotalSignificance"], config["bkgdCorrAve"], config["bkgdCorrStd"])

            totMetric = config["Achi2ndof"]
            tDict["%s/%s/"%(args.subdir,training)] = totMetric
            mDict[totMetric] = "N / A" 
        else:
            tDict["%s/%s/"%(args.subdir,training)] = 999.0
            mDict[999.0] = "N / A"
            
        f.close()

    temp = sorted(tDict.items(), key=operator.itemgetter(1), reverse=False)

    sortedTrainings = collections.OrderedDict(temp) 

    nTrainings = len(sortedTrainings)

    nTalks = int(math.ceil(float(nTrainings) / float(stop)))

    talks = []
    for nTalk in range(0, nTalks):
        talks.append(open("%s/%s_Double_DisCo_Stealth_Stop_Meeting_%s_%d.tex"%(args.inputDir,date1,args.subdir,nTalk), "w"))
        writeHeader(talks[nTalk], date2, " ".join(args.title))

    count = 0
    for plotDir, metric in sortedTrainings.items():

        if not os.path.isdir("%s/%s"%(args.inputDir,plotDir)): continue

        temp = os.listdir("%s/%s"%(args.inputDir,plotDir))

        if len(temp) < 5: continue

        count += 1

        iTalk = int(count / stop)

        writeSlide1(talks[iTalk], mDict[metric], args.inputDir, plotDir, plotDir.replace("_","\_"))
        #writeSlide2(talks[iTalk], args.inputDir, plotDir, plotDir.replace("_","\_"))

    for talk in talks:
        writeFooter(talk)
        talk.close()
